### ISSUE TITLE
Improve eSCAPE HPCC installation instructions

### ISSUE THREAD

**Issue by kbarnhart** [Geodels/eSCAPE#3]
This is another issue associated with [this JOSS review](https://github.com/openjournals/joss-reviews/issues/964).

I downloaded and tested the Docker image (and as expected it worked). I wanted to also test the HPCC installation instructions as I would expect that most full-scale applications would use eSCAPE installed in this way. 

I'm still in the process of doing this install so I can't yet report if I've been successful. However, thus far I have some comments on the [Install on HPC wiki page](https://github.com/Geodels/eSCAPE/wiki/Installation-on-HPC).

Specifically, rather than providing what seems to be a set of instructions that have worked on one particular HPC platform, I'd recommend listing the following: 

- a list of required compilers
- a statement about what major.minor versions of python eSCAPE is compatible with (2.7. 3.5, 3.6?)
- a package management file that lists the standard python packages (e.g. `numpy`) and minimum version requirements so that these can be installed with `pip` or `conda`. 
- a list of the more customized python packages that must be installed by cloning a repo and compiling.
- a statement about the version of PETSc required for running eSCAPE.

Its also a bit confusing to my why the  [installing petsc4py locally](https://github.com/Geodels/eSCAPE/wiki/Installation-on-HPC#installing-petsc-petsc4py-locally) section is located after the statements about compiling eSCAPE.

**Comment by tristan-salles** [comment]
Based on reviewer's comment I have updated the wiki page and also the model website:
+ [Installation](https://github.com/Geodels/eSCAPE/wiki/Installation-on-HPC)

**Comment by kbarnhart** [comment]
The updates to the documentation look great @tristan-salles ! I'll try them out on the HPC I have access to and report back if I run into any problems.

**Comment by kbarnhart** [comment]
A minor comment:   `pandas` is listed with pip install but not listed under standard packages.

**Comment by kbarnhart** [comment]
Comments related to the `petsc4py` installation

First, a minor one:  I think the statement `(see next section if you need to build petsc locally...)` should refer to petsc4py instead of petsc.

Second, my HPC platform already has `petsc4py` installed, the environment variable `$PETSC_DIR` is already set, and when I try and install the package I get the following message:


```
[barnhark@shas0136 barnhark]$ pip install petsc4py --user
Requirement already satisfied: petsc4py in /curc/sw/petsc/3.8.0/impi/17.3/intel/17.4/petsc4py/lib/python2.7/site-packages
Requirement already satisfied: numpy in /curc/sw/python/2.7.11/lib/python2.7/site-packages (from petsc4py)
```

Thus I'd recommend revising the two sections that have to do with petsc to say something like the following:

> eSCAPE requires the PETSc library and petsc4py package. Here we will not describe compiling the PETSc library as it is often a default module available on HPC platforms. 

> Depending on your particular HPC platform `petsc4py` may already be installed, a standard `pip install` will work, or you may need to compile `petsc4py` from scratch

Below this introduction, you can then recycle the text you've created. I'd recommend including an example of how a user would know that they already have `petsc4py` installed. 

and a final minor comment about `petsc4py`. I'd change the two statement `export PETSC_DIR=...` to acknowledge that other HPC may have a different location for the `$PETSC_DIR`. Perhaps something like:  `export PETSC_DIR=\path\to\petsc\location`

**Comment by tristan-salles** [comment]
> Comments related to the `petsc4py` installation
> 
> First, a minor one: I think the statement `(see next section if you need to build petsc locally...)` should refer to petsc4py instead of petsc.
> 
> Second, my HPC platform already has `petsc4py` installed, the environment variable `$PETSC_DIR` is already set, and when I try and install the package I get the following message:
> 
> ```
> [barnhark@shas0136 barnhark]$ pip install petsc4py --user
> Requirement already satisfied: petsc4py in /curc/sw/petsc/3.8.0/impi/17.3/intel/17.4/petsc4py/lib/python2.7/site-packages
> Requirement already satisfied: numpy in /curc/sw/python/2.7.11/lib/python2.7/site-packages (from petsc4py)
> ```
> Thus I'd recommend revising the two sections that have to do with petsc to say something like the following:
> 
> > eSCAPE requires the PETSc library and petsc4py package. Here we will not describe compiling the PETSc library as it is often a default module available on HPC platforms.
> 
> > Depending on your particular HPC platform `petsc4py` may already be installed, a standard `pip install` will work, or you may need to compile `petsc4py` from scratch
> 
> Below this introduction, you can then recycle the text you've created. I'd recommend including an example of how a user would know that they already have `petsc4py` installed.
> 
> and a final minor comment about `petsc4py`. I'd change the two statement `export PETSC_DIR=...` to acknowledge that other HPC may have a different location for the `$PETSC_DIR`. Perhaps something like: `export PETSC_DIR=\path\to\petsc\location`

I've updated the documentation in the wiki based on recommended changes

**Comment by tristan-salles** [comment]
Now regarding the installation issue. It looks like you are using the intel compilers, did you install `fillit` and `eSCAPE` using the following commands:
```bash
export F90=ifort
git clone https://github.com/Geodels/fillit.git
cd fillit
python setup.py install --user

git clone https://github.com/Geodels/eSCAPE.git
cd eSCAPE
python setup.py install --user
```
with first `export F90=ifort` specified.

**Comment by kbarnhart** [comment]
@tristan-salles 

It looks like I forgot to include the lines that deal with installing `eSCAPE` and `fillit`. Sorry about that. I did execute `export F9=ifort` first. 

I just checked the `ifort` version and it is older than the one you list. Don't know if that may be a problem.
```
[barnhark@shas0137 barnhark]$ ifort --version
ifort (IFORT) 17.0.4 20170411
Copyright (C) 1985-2017 Intel Corporation.  All rights reserved.
```

Based on a bit more debugging I think I have one issue related to the fortran compiler and one issue related to `petsc4py`.

Looking more closely at the terminal log that prints when I compile `fillit` and `eSCAPE` I see that I'm getting some warnings associated with not finding fortran compilers.  I assume I shouldn't be getting these fortran compiler warnings. 

```
[barnhark@shas0137 barnhark]$ module purge
[barnhark@shas0137 barnhark]$ ml intel/17.4  impi/17.3
[barnhark@shas0137 barnhark]$ ml petsc/3.8.0
[barnhark@shas0137 barnhark]$ ml hdf5
[barnhark@shas0137 barnhark]$ export F90=ifort
[barnhark@shas0137 barnhark]$ cd fillit
[barnhark@shas0137 fillit]$ python setup.py install --user
make: Entering directory `/projects/barnhark/fillit/src'
ifort -shared -O2 -fPIC -c queues.f90
make: Leaving directory `/projects/barnhark/fillit/src'
/curc/sw/python/2.7.11/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "fillit._fillBarnes" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7' to include_dirs.
building extension "fillit._fillWei" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7' to include_dirs.
building extension "fillit._fillZhou" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7' to include_dirs.
building data_files sources
build_src: building npy-pkg config files
writing fillit.egg-info/PKG-INFO
writing top-level names to fillit.egg-info/top_level.txt
writing dependency_links to fillit.egg-info/dependency_links.txt
reading manifest template 'MANIFEST.in'
warning: no files found matching 'fillit/Notebooks'
writing manifest file 'fillit.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /curc/sw/intel/17.4/compilers_and_libraries_2017.4.196/linux/bin/intel64/ifort
Found executable /curc/sw/intel/17.4/compilers_and_libraries_2017.4.196/linux/bin/intel64/xild
Found executable /curc/sw/intel/17.4/compilers_and_libraries_2017.4.196/linux/bin/intel64/xiar
Found executable /curc/sw/gcc/5.4.0/bin/gfortran
customize IntelFCompiler
customize LaheyFCompiler
Could not locate executable lf95
lahey: no Fortran 77 compiler found
lahey: no Fortran 77 compiler found
customize PGroupFCompiler
Could not locate executable pgfortran
pg: no Fortran 77 compiler found
pg: no Fortran 77 compiler found
customize AbsoftFCompiler
Could not locate executable f77
absoft: no Fortran 77 compiler found
absoft: no Fortran 77 compiler found
customize NAGFCompiler
Found executable /usr/bin/f95
customize VastFCompiler
customize CompaqFCompiler
Could not locate executable fort
compaq: no Fortran 77 compiler found
compaq: no Fortran 77 compiler found
customize IntelItaniumFCompiler
customize IntelEM64TFCompiler
customize IntelEM64TFCompiler
customize IntelEM64TFCompiler using build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/fillit
copying build/lib.linux-x86_64-2.7/fillit/queuepit.py -> build/bdist.linux-x86_64/egg/fillit
copying build/lib.linux-x86_64-2.7/fillit/_fillWei.so -> build/bdist.linux-x86_64/egg/fillit
copying build/lib.linux-x86_64-2.7/fillit/pitZhou.py -> build/bdist.linux-x86_64/egg/fillit
copying build/lib.linux-x86_64-2.7/fillit/pitBarnes.py -> build/bdist.linux-x86_64/egg/fillit
copying build/lib.linux-x86_64-2.7/fillit/pitWei.py -> build/bdist.linux-x86_64/egg/fillit
copying build/lib.linux-x86_64-2.7/fillit/_fillZhou.so -> build/bdist.linux-x86_64/egg/fillit
copying build/lib.linux-x86_64-2.7/fillit/__init__.py -> build/bdist.linux-x86_64/egg/fillit
copying build/lib.linux-x86_64-2.7/fillit/_fillBarnes.so -> build/bdist.linux-x86_64/egg/fillit
byte-compiling build/bdist.linux-x86_64/egg/fillit/queuepit.py to queuepit.pyc
byte-compiling build/bdist.linux-x86_64/egg/fillit/pitZhou.py to pitZhou.pyc
byte-compiling build/bdist.linux-x86_64/egg/fillit/pitBarnes.py to pitBarnes.pyc
byte-compiling build/bdist.linux-x86_64/egg/fillit/pitWei.py to pitWei.pyc
byte-compiling build/bdist.linux-x86_64/egg/fillit/__init__.py to __init__.pyc
creating stub loader for fillit/_fillBarnes.so
creating stub loader for fillit/_fillWei.so
creating stub loader for fillit/_fillZhou.so
byte-compiling build/bdist.linux-x86_64/egg/fillit/_fillBarnes.py to _fillBarnes.pyc
byte-compiling build/bdist.linux-x86_64/egg/fillit/_fillWei.py to _fillWei.pyc
byte-compiling build/bdist.linux-x86_64/egg/fillit/_fillZhou.py to _fillZhou.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
copying src/queues.o -> build/bdist.linux-x86_64/egg/fillit
copying src/queues.mod -> build/bdist.linux-x86_64/egg/fillit
running install_clib
customize UnixCCompiler
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying fillit.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fillit.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fillit.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fillit.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/fillit-0.0.1-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing fillit-0.0.1-py2.7-linux-x86_64.egg
Removing /home/barnhark/.local/lib/python2.7/site-packages/fillit-0.0.1-py2.7-linux-x86_64.egg
Copying fillit-0.0.1-py2.7-linux-x86_64.egg to /home/barnhark/.local/lib/python2.7/site-packages
fillit 0.0.1 is already the active version in easy-install.pth

Installed /home/barnhark/.local/lib/python2.7/site-packages/fillit-0.0.1-py2.7-linux-x86_64.egg
Processing dependencies for fillit==0.0.1
Finished processing dependencies for fillit==0.0.1
[barnhark@shas0137 fillit]$ cd ../eSCAPE
[barnhark@shas0137 eSCAPE]$ python setup.py install --user
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "eSCAPE._fortran" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7' to include_dirs.
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /curc/sw/intel/17.4/compilers_and_libraries_2017.4.196/linux/bin/intel64/ifort
Found executable /curc/sw/intel/17.4/compilers_and_libraries_2017.4.196/linux/bin/intel64/xild
Found executable /curc/sw/intel/17.4/compilers_and_libraries_2017.4.196/linux/bin/intel64/xiar
Found executable /curc/sw/gcc/5.4.0/bin/gfortran
customize IntelFCompiler
customize LaheyFCompiler
Could not locate executable lf95
lahey: no Fortran 77 compiler found
lahey: no Fortran 77 compiler found
customize PGroupFCompiler
Could not locate executable pgfortran
pg: no Fortran 77 compiler found
pg: no Fortran 77 compiler found
customize AbsoftFCompiler
Could not locate executable f77
absoft: no Fortran 77 compiler found
absoft: no Fortran 77 compiler found
customize NAGFCompiler
Found executable /usr/bin/f95
customize VastFCompiler
customize CompaqFCompiler
Could not locate executable fort
compaq: no Fortran 77 compiler found
compaq: no Fortran 77 compiler found
customize IntelItaniumFCompiler
customize IntelEM64TFCompiler
customize IntelEM64TFCompiler
customize IntelEM64TFCompiler using build_ext
running install_lib
running install_egg_info
Removing /home/barnhark/.local/lib/python2.7/site-packages/eSCAPE-0.1-py2.7.egg-info
Writing /home/barnhark/.local/lib/python2.7/site-packages/eSCAPE-0.1-py2.7.egg-info
running install_clib
customize UnixCCompiler
```

The second issue relates to `petsc4py`. I think that recommending that a user test that list of package imports would be great as it identified that my import issues start with `petsc4py`. 

```python
>>> from petsc4py import PETSc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/curc/sw/petsc/3.8.0/impi/17.3/intel/17.4/petsc4py/lib/python2.7/site-packages/petsc4py/PETSc.py", line 6, in <module>
    PETSc = ImportPETSc(ARCH)
  File "/curc/sw/petsc/3.8.0/impi/17.3/intel/17.4/petsc4py/lib/python2.7/site-packages/petsc4py/lib/__init__.py", line 29, in ImportPETSc
    return Import('petsc4py', 'PETSc', path, arch)
  File "/curc/sw/petsc/3.8.0/impi/17.3/intel/17.4/petsc4py/lib/python2.7/site-packages/petsc4py/lib/__init__.py", line 64, in Import
    with f: module = imp.load_module(fullname, f, fn, info)
ImportError: /curc/sw/intel/17.4/mkl/lib/intel64/libmkl_sequential.so: undefined symbol: mkl_sparse_d_csr__g_n_syrk_notr_row_struct_i8
```

I'm getting my `petsc4py` package as part of a module that CU Research computing has built, so I'll ask them for help fixing that issue. 

A very simple test of my `petsc4py` is as follows (and fails)

```
[barnhark@shas0137 barnhark]$ module purge
[barnhark@shas0137 barnhark]$ ml intel/17.4  impi/17.3
[barnhark@shas0137 barnhark]$ ml petsc/3.8.0
[barnhark@shas0137 barnhark]$ python
Python 2.7.11 (default, Mar 22 2016, 01:42:54)
[GCC Intel(R) C++ gcc 4.8 mode] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import petsc4py
>>> petsc4py.__version__
'3.8.1'
>>> from petsc4py import PETSc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/curc/sw/petsc/3.8.0/impi/17.3/intel/17.4/petsc4py/lib/python2.7/site-packages/petsc4py/PETSc.py", line 6, in <module>
    PETSc = ImportPETSc(ARCH)
  File "/curc/sw/petsc/3.8.0/impi/17.3/intel/17.4/petsc4py/lib/python2.7/site-packages/petsc4py/lib/__init__.py", line 29, in ImportPETSc
    return Import('petsc4py', 'PETSc', path, arch)
  File "/curc/sw/petsc/3.8.0/impi/17.3/intel/17.4/petsc4py/lib/python2.7/site-packages/petsc4py/lib/__init__.py", line 64, in Import
    with f: module = imp.load_module(fullname, f, fn, info)
ImportError: /curc/sw/intel/17.4/mkl/lib/intel64/libmkl_sequential.so: undefined symbol: mkl_sparse_d_csr__g_n_syrk_notr_row_struct_i8
```

**Comment by tristan-salles** [comment]
Hi Katy,
The warnings are fine as the compilation is looking for potential compilers, below is the log for my compilation on USyD HPC:

```bash
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "eSCAPE._fortran" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran' to include_dirs.
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
C compiler: icc -pthread -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/local/hdf5/1.8.14/include -I/usr/local/petsc-intel-mpi/3.9.3/include -I/usr/local/python/2.7.15-intel/include -I/usr/local/zlib/1.2.8/include -I/usr/local/cgal/4.9/include -I/usr/local/boost/1.64.0/include -I/usr/local/bzip2/1.0.6/include -I/usr/local/cairo/1.14.10/include -I/usr/local/ncurses/5.9/include -I/usr/local/libcroco/0.6.8/include -I/usr/local/openjpeg/2.1.0/include -I/usr/local/libcurl/7.40.0/include -I/usr/local/poppler/0.31.0/include -I/usr/local/libffi/3.2.1/include -I/usr/local/libspectre/0.2.7/include -I/usr/local/ghostscript/9.15/include -I/usr/local/perl/5.20.1/include -I/usr/local/glib/2.34.0/include -I/usr/local/harfbuzz/0.9.38/include -I/usr/local/libxml2/2.9.2/include -I/usr/local/pango/1.36.8/include -I/usr/local/pixman/0.32.6/include -I/usr/local/readline/6.3/include -I/usr/local/freetype/2.5.5/include -I/usr/local/pcre2/10.00/include -I/usr/local/libjpeg/6b/include -I/usr/local/fontconfig/2.11.92/include -I/usr/local/libtiff/4.0.3/include -I/usr/local/libpng/1.6.16/include -I/usr/local/openssl/1.1.0h/include -I/usr/local/gcc/4.9.3/include -I/usr/local/mpfr/3.1.4/include -I/usr/local/gmp/5.1.3/include -I/usr/local/hdf5/1.8.14/include -I/usr/local/petsc-intel-mpi/3.9.3/include -I/usr/local/python/2.7.15-intel/include -I/usr/local/zlib/1.2.8/include -I/usr/local/cgal/4.9/include -I/usr/local/boost/1.64.0/include -I/usr/local/bzip2/1.0.6/include -I/usr/local/cairo/1.14.10/include -I/usr/local/ncurses/5.9/include -I/usr/local/libcroco/0.6.8/include -I/usr/local/openjpeg/2.1.0/include -I/usr/local/libcurl/7.40.0/include -I/usr/local/poppler/0.31.0/include -I/usr/local/libffi/3.2.1/include -I/usr/local/libspectre/0.2.7/include -I/usr/local/ghostscript/9.15/include -I/usr/local/perl/5.20.1/include -I/usr/local/glib/2.34.0/include -I/usr/local/harfbuzz/0.9.38/include -I/usr/local/libxml2/2.9.2/include -I/usr/local/pango/1.36.8/include -I/usr/local/pixman/0.32.6/include -I/usr/local/readline/6.3/include -I/usr/local/freetype/2.5.5/include -I/usr/local/pcre2/10.00/include -I/usr/local/libjpeg/6b/include -I/usr/local/fontconfig/2.11.92/include -I/usr/local/libtiff/4.0.3/include -I/usr/local/libpng/1.6.16/include -I/usr/local/openssl/1.1.0h/include -I/usr/local/gcc/4.9.3/include -I/usr/local/mpc/1.0.3/include -I/usr/local/mpfr/3.1.4/include -I/usr/local/gmp/5.1.3/include -fPIC

creating /tmp/tmpYrARDS/tmp
creating /tmp/tmpYrARDS/tmp/tmpYrARDS
compile options: '-MMD -MF /tmp/tmpYrARDS/file.c.d -c'
icc: /tmp/tmpYrARDS/file.c
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Found executable /usr/local/intel/18.1/bin/ifort
Found executable /usr/local/gcc/4.9.3/bin/gfortran
customize IntelFCompiler
customize LaheyFCompiler
Could not locate executable lf95
lahey: no Fortran 77 compiler found
lahey: no Fortran 77 compiler found
customize PGroupFCompiler
Could not locate executable pgfortran
pg: no Fortran 77 compiler found
pg: no Fortran 77 compiler found
customize AbsoftFCompiler
Could not locate executable f77
absoft: no Fortran 77 compiler found
absoft: no Fortran 77 compiler found
customize NAGFCompiler
Found executable /usr/bin/f95
customize VastFCompiler
customize CompaqFCompiler
Could not locate executable fort
compaq: no Fortran 77 compiler found
compaq: no Fortran 77 compiler found
customize IntelItaniumFCompiler
customize IntelEM64TFCompiler
customize IntelEM64TFCompiler
customize IntelEM64TFCompiler using build_ext
running install_lib
running install_egg_info
Removing /home/tsalles/.local/lib/python2.7/site-packages/eSCAPE-0.1-py2.7.egg-info
Writing /home/tsalles/.local/lib/python2.7/site-packages/eSCAPE-0.1-py2.7.egg-info
running install_clib
customize UnixCCompiler
C compiler: icc -pthread -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/local/hdf5/1.8.14/include -I/usr/local/petsc-intel-mpi/3.9.3/include -I/usr/local/python/2.7.15-intel/include -I/usr/local/zlib/1.2.8/include -I/usr/local/cgal/4.9/include -I/usr/local/boost/1.64.0/include -I/usr/local/bzip2/1.0.6/include -I/usr/local/cairo/1.14.10/include -I/usr/local/ncurses/5.9/include -I/usr/local/libcroco/0.6.8/include -I/usr/local/openjpeg/2.1.0/include -I/usr/local/libcurl/7.40.0/include -I/usr/local/poppler/0.31.0/include -I/usr/local/libffi/3.2.1/include -I/usr/local/libspectre/0.2.7/include -I/usr/local/ghostscript/9.15/include -I/usr/local/perl/5.20.1/include -I/usr/local/glib/2.34.0/include -I/usr/local/harfbuzz/0.9.38/include -I/usr/local/libxml2/2.9.2/include -I/usr/local/pango/1.36.8/include -I/usr/local/pixman/0.32.6/include -I/usr/local/readline/6.3/include -I/usr/local/freetype/2.5.5/include -I/usr/local/pcre2/10.00/include -I/usr/local/libjpeg/6b/include -I/usr/local/fontconfig/2.11.92/include -I/usr/local/libtiff/4.0.3/include -I/usr/local/libpng/1.6.16/include -I/usr/local/openssl/1.1.0h/include -I/usr/local/gcc/4.9.3/include -I/usr/local/mpfr/3.1.4/include -I/usr/local/gmp/5.1.3/include -I/usr/local/hdf5/1.8.14/include -I/usr/local/petsc-intel-mpi/3.9.3/include -I/usr/local/python/2.7.15-intel/include -I/usr/local/zlib/1.2.8/include -I/usr/local/cgal/4.9/include -I/usr/local/boost/1.64.0/include -I/usr/local/bzip2/1.0.6/include -I/usr/local/cairo/1.14.10/include -I/usr/local/ncurses/5.9/include -I/usr/local/libcroco/0.6.8/include -I/usr/local/openjpeg/2.1.0/include -I/usr/local/libcurl/7.40.0/include -I/usr/local/poppler/0.31.0/include -I/usr/local/libffi/3.2.1/include -I/usr/local/libspectre/0.2.7/include -I/usr/local/ghostscript/9.15/include -I/usr/local/perl/5.20.1/include -I/usr/local/glib/2.34.0/include -I/usr/local/harfbuzz/0.9.38/include -I/usr/local/libxml2/2.9.2/include -I/usr/local/pango/1.36.8/include -I/usr/local/pixman/0.32.6/include -I/usr/local/readline/6.3/include -I/usr/local/freetype/2.5.5/include -I/usr/local/pcre2/10.00/include -I/usr/local/libjpeg/6b/include -I/usr/local/fontconfig/2.11.92/include -I/usr/local/libtiff/4.0.3/include -I/usr/local/libpng/1.6.16/include -I/usr/local/openssl/1.1.0h/include -I/usr/local/gcc/4.9.3/include -I/usr/local/mpc/1.0.3/include -I/usr/local/mpfr/3.1.4/include -I/usr/local/gmp/5.1.3/include -fPIC

creating /tmp/tmpoA0Nl3/tmp
creating /tmp/tmpoA0Nl3/tmp/tmpoA0Nl3
compile options: '-MMD -MF /tmp/tmpoA0Nl3/file.c.d -c'
icc: /tmp/tmpoA0Nl3/file.c
``` 

Yes I will add the import test in the wiki installation

**Comment by kbarnhart** [comment]
I wanted to give a quick update on my end here. 

I think that the remaining compilation errors are related to my HPC platform (my use of `petsc4py` uncovered that it hadn't been compiled correctly against MKL). Thats been fixed. I still haven't successfully compiled `fillit` or `eSCAPE`. The errors are related to `__stack_chk_guard` which CU RC staff has told me is related to Intel switching the version of GCC used on the backend (and that they've seen these errors come up before related to compiling python packages). 

They are helping me work through this and I expect to have things ironed out Friday/tomorrow or early next week. Ideally I'd like to successfully compile and run `eSCAPE` on an HPC before I finalize my review. However, if I encounter additional delays associated with libraries/compilers available on the HPC platform I am working on I won't let this delay my finalizing a review in a reasonable timeline.

**Comment by kbarnhart** [comment]
@tristan-salles thanks for these improvements! I'm closing this issue.
