### ISSUE TITLE
PETSC ERROR occur when testing examples

### ISSUE THREAD

**Issue by tyszwh** [Geodels/eSCAPE#8]
Hi, Dr Sallles

I test the demo (bluemountain) with PETSC-version from 3.8.4 to 3.10.5 under env of Python 3.7. All of them show error message as follows:

```
Petsc Release Version 3.8.4, Mar, 24, 2018 
       The PETSc Team
    petsc-maint@mcs.anl.gov
 http://www.mcs.anl.gov/petsc/
See docs/changes/index.html for recent updates.
See docs/faq.html for problems.
See docs/manualpages/index.html for help. 
Libraries linked from /home/litho/Programs/petsc-3.8.4-opt/lib
--------------------------------------------------------------------------
Input file: input_bluemountains.yml
 Verbose is on? True
 PETSC log is on? True
The following model will be run:     Regional model
Extract information (0.00 seconds)
Reading meshplex meshtri (0.23 seconds)
Mark boundary TIN (1.07 seconds)
Defining edges TIN (1.04 seconds)
Defining global TIN (0.09 seconds)
Reading mesh information (2.44 seconds)
Create DMPlex (1.41 seconds)
Distribute DMPlex (0.29 seconds)
Distribute field to DMPlex (0.12 seconds)
Creating Petsc DMPlex (1.82 seconds)
Defining local DMPlex (2.53 seconds)
Voronoi creation (1.58 seconds)
Tesselation (0.67 seconds)
Finite volume mesh declaration (9.14 seconds)
Priority-flood algorithm initialisation (0.38 seconds)
Update External Forces (0.04 seconds)
--- Initialisation Phase (11.73 seconds)
Flow Direction declaration (0.09 seconds)
Compute Flow Accumulation (5.86 seconds)
Creating outputfile (0.82 seconds)
+++ Output Simulation Time: 0.00 years
Get Erosion Thicknesses (2.27 seconds)
Update Sediment Load (4.24 seconds)
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[0]PETSC ERROR: to get more information on the crash.
application called MPI_Abort(MPI_COMM_WORLD, 59) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=59
:
system msg for write_line failure : Bad file descriptor
```
So, where does the problem arise?

**Comment by tristan-salles** [comment]
I made some tests on the docker/kitematic version and on our cluster (both of them use python 2.7) and all examples are working... 
Have you tried with python 2.7 and is the problem still happening?

**Comment by tyszwh** [comment]
Ok，I have tried within the ENV of python 2.7, but I found a different error occurred as follows. 
--------------------------------------------------------------------------
```
Petsc Release Version 3.10.5, Mar, 28, 2019 
       The PETSc Team
    petsc-maint@mcs.anl.gov
 http://www.mcs.anl.gov/petsc/
See docs/changes/index.html for recent updates.
See docs/faq.html for problems.
See docs/manualpages/index.html for help. 
Libraries linked from /home/build/petscsource/petsc-3.10.5/opt/lib
--------------------------------------------------------------------------
Input file: input_bluemountains.yml
 Verbose is on? True
 PETSC log is on? True
The following model will be run:     Regional model
Extract information (0.00 seconds)
Reading meshplex meshtri (0.28 seconds)
Mark boundary TIN (1.08 seconds)
Defining edges TIN (1.05 seconds)
Defining global TIN (0.09 seconds)
Reading mesh information (2.52 seconds)
Create DMPlex (1.70 seconds)
Distribute DMPlex (0.24 seconds)
Distribute field to DMPlex (0.13 seconds)
Creating Petsc DMPlex (2.07 seconds)
Defining local DMPlex (2.05 seconds)
Voronoi creation (1.68 seconds)
Tesselation (0.73 seconds)
Finite volume mesh declaration (9.14 seconds)
Priority-flood algorithm initialisation (0.39 seconds)
Update External Forces (0.04 seconds)
--- Initialisation Phase (10.82 seconds)
Flow Direction declaration (0.09 seconds)
Compute Flow Accumulation (5.09 seconds)
Creating outputfile (0.82 seconds)
+++ Output Simulation Time: 0.00 years
Get Erosion Thicknesses (1.37 seconds)
Update Sediment Load (4.34 seconds)
Traceback (most recent call last):
  File "run_escape.py", line 20, in <module>
    model.runProcesses()
  File "/usr/local/lib/python2.7/dist-packages/eSCAPE/__init__.py", line 162, in runProcesses
    _UnstPit.getDepressions(self)
  File "/usr/local/lib/python2.7/dist-packages/eSCAPE/pit/pitfillunst.py", line 125, in getDepressions
    fill,wshed,pitvol,pith,pitNode = self.eScapeGPit.performPitFillingEpsilon(melev,seaIDs,eps,type=1)
  File "build/bdist.linux-x86_64/egg/fillit/pitScape.py", line 97, in performPitFillingEpsilon
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)
```

**Comment by tristan-salles** [comment]
It seems to be an issue related to f2py, I have made some changes on **fillit** repo. Could you reclone and install this repo again and rerun the experiment? 

```bash
git clone https://github.com/Geodels/fillit.git
cd fillit 
export F90=gfortran 
cd src 
make all 
cd .. 
python setup.py install
```

**Comment by tyszwh** [comment]
OK, I reinstalled this repo again, and now the model runs correctly within ENV of Python2. I will test other demos. 
For Env of Python3, I guess some problem with linking to PEtsc or Petsc4py. The different error occurs with petsc 3.11.1 compared with previous petsc version.

**Comment by tristan-salles** [comment]
Good to know that it worked! You can try to run with Python3 to check if it also solved the issue you had as well... :earth_asia:

**Comment by tyszwh** [comment]
I have tried in Env of python3. The same error still exists 

```
Petsc Release Version 3.10.5, Mar, 28, 2019 
       The PETSc Team
    petsc-maint@mcs.anl.gov
 http://www.mcs.anl.gov/petsc/
See docs/changes/index.html for recent updates.
See docs/faq.html for problems.
See docs/manualpages/index.html for help. 
Libraries linked from /home/build/petscsource/petsc-3.10.5/opt/lib
--------------------------------------------------------------------------
Input file: input_bluemountains.yml
 Verbose is on? True
 PETSC log is on? True
The following model will be run:     Regional model
Extract information (0.01 seconds)
Reading meshplex meshtri (0.29 seconds)
Mark boundary TIN (1.13 seconds)
Defining edges TIN (1.10 seconds)
Defining global TIN (0.10 seconds)
Reading mesh information (2.62 seconds)
Create DMPlex (1.77 seconds)
Distribute DMPlex (0.30 seconds)
Distribute field to DMPlex (0.12 seconds)
Creating Petsc DMPlex (2.19 seconds)
Defining local DMPlex (2.57 seconds)
Voronoi creation (1.65 seconds)
Tesselation (0.76 seconds)
Finite volume mesh declaration (9.88 seconds)
Priority-flood algorithm initialisation (0.39 seconds)
Update External Forces (0.04 seconds)
--- Initialisation Phase (11.58 seconds)
Flow Direction declaration (0.09 seconds)
Compute Flow Accumulation (5.13 seconds)
Creating outputfile (0.82 seconds)
+++ Output Simulation Time: 0.00 years
Get Erosion Thicknesses (1.37 seconds)
Update Sediment Load (4.38 seconds)
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[0]PETSC ERROR: to get more information on the crash.
application called MPI_Abort(MPI_COMM_WORLD, 59) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=59
:
system msg for write_line failure : Bad file descriptor
```

**Comment by tristan-salles** [comment]
Yeah it looks like an issue with your installation of Petsc and/or MPI... You seem to run the code in serial, are you using the following command line:
```bash
mpirun -np 1 python run_escape.py -I input_australia.yml
```
and did you try a parallel run...

There are several threads reporting similar issues on google and they seems to be related to local installation problems...  
- [segfault](https://bitbucket.org/fenics-project/dolfin/issues/860/segmentation-violation-while-constructing)

**Comment by tyszwh** [comment]
Yes, I tried the mpirun. The error is the same compared with the serial run.


```
mpirun -np 1 python3 run_escape.py -i input_bluemountains.yml -v -l
--------------------------------------------------------------------------
Petsc Release Version 3.10.5, Mar, 28, 2019 
       The PETSc Team
    petsc-maint@mcs.anl.gov
 http://www.mcs.anl.gov/petsc/
See docs/changes/index.html for recent updates.
See docs/faq.html for problems.
See docs/manualpages/index.html for help. 
Libraries linked from /home/build/petscsource/petsc-3.10.5/opt/lib
--------------------------------------------------------------------------
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[0]PETSC ERROR: to get more information on the crash.
application called MPI_Abort(MPI_COMM_WORLD, 59) - process 0
```

**Comment by tristan-salles** [comment]
If this is an installation issue with some conflicting libraries I cannot be of any help... I'm glad it is working with python 2.7 😄 
I will close the comment.
