### ISSUE TITLE
improve installation instructions for petsc

### ISSUE THREAD

**Issue by johnjarmitage** [Geodels/eSCAPE#9]
I am trying to install eSCAPE on my system (ubuntu 18.04.2 LTS). I found the petsc instructions are are not sufficient. I needed to add the flags:

--with-cc=gcc --with-cxx=g++ --with-fc=gfortran --download-mpich

I don't know if this is system specific, but I think not. I am happy to make a PR to update the instructions.

**Comment by johnjarmitage** [comment]
In fact, even with this I am still struggling. I am having better success with conda to install the dependencies.

**Comment by johnjarmitage** [comment]
OK, I failed to install with the instructions (probably my fault). I have managed to almost get there with conda. I run the eSCAPE setup.py, and except from some tab inconsistencies, which I fixed, there are no warnings or errors. However, the `eSCPAE._fortran`  module has not been created:

```
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eSCAPE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/armitage/code/eSCAPE/eSCAPE/__init__.py", line 70, in <module>
    from .mesher import UnstMesh as _UnstMesh
  File "/home/armitage/code/eSCAPE/eSCAPE/mesher/__init__.py", line 23, in <module>
    from .unstructuredmesh import UnstMesh
  File "/home/armitage/code/eSCAPE/eSCAPE/mesher/unstructuredmesh.py", line 31, in <module>
    from eSCAPE._fortran import defineGTIN
ModuleNotFoundError: No module named 'eSCAPE._fortran'
```
Here is the output from the `python setup.py install`:
```
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "eSCAPE._fortran" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/fortran/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/fortran' to include_dirs.
Reading .f2py_f2cmap ...
	Mapping "integer(kind=HANDLE_KIND)" to "long"
	Mapping "integer(kind=handle_kind)" to "long"
Successfully applied user defined changes from .f2py_f2cmap
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
running install_lib
running install_egg_info
Removing /home/armitage/anaconda3/envs/escape/lib/python3.6/site-packages/eSCAPE-0.1-py3.6.egg-info
Writing /home/armitage/anaconda3/envs/escape/lib/python3.6/site-packages/eSCAPE-0.1-py3.6.egg-info
running install_clib
customize UnixCCompiler
```
Any advice as to where I have gone wrong would be great, as I cannot see any error message.

**Comment by tristan-salles** [comment]
Hi @johnjarmitage and sorry for the pain...

I will suggest removing the _build_ folder from the **eSCAPE** repo as well as from the site-packages...

```bash
rm -rf /home/armitage/code/eSCAPE/eSCAPE/build
rm -rf /home/armitage/anaconda3/envs/escape/lib/python3.6/site-packages/eSCAPE
rm -rf /home/armitage/anaconda3/envs/escape/lib/python3.6/site-packages/eSCAPE-0.1-py3.6.egg-info
```

Then to redo the _setup install_ command
```bash
cd /home/armitage/code/eSCAPE/eSCAPE/
python3.6 setup.py install
```

When running the following 
```bash
ls  /home/armitage/anaconda3/envs/escape/lib/python3.6/site-packages/eSCAPE
```
 You should have the **_fortran.so** library present as part of the distribution. If this is the case then you have a linking problem in the _conda_ environment, did you use a virtual env? If the  **_fortran.so** library isn't present the `python3.6 setup.py install` script will have hopefully returned some error messages...

***
Below is the output of my setup installation message for python2.7...
 
```
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "eSCAPE._fortran" sources
creating build
creating build/src.linux-x86_64-2.7
creating build/src.linux-x86_64-2.7/fortran
f2py options: []
f2py: fortran/functions.pyf

Reading .f2py_f2cmap ...
	Mapping "integer(kind=HANDLE_KIND)" to "long"
	Mapping "integer(kind=handle_kind)" to "long"
Successfully applied user defined changes from .f2py_f2cmap
Reading fortran codes...
	Reading file 'fortran/functions.pyf' (format:free)
rmbadname1: Replacing "rank" with "rank_bn".
rmbadname1: Replacing "rank" with "rank_bn".
Post-processing...
	Block: _fortran
			Block: meanSlope
			Block: flatBounds
			Block: slpBounds
			Block: setHillslopeCoeff
			Block: setDiffusionCoeff
			Block: explicitDiff
			Block: distributeHeight
			Block: distributeVolume
			Block: diffusionDT
			Block: minHeight
			Block: pitData
			Block: MFDreceivers
			Block: defineTIN
			Block: defineGTIN
Post-processing (stage 2)...
Building modules...
	Building module "_fortran"...
		Constructing wrapper function "meanSlope"...
		  bslp = meanSlope(elev,bid,gbounds,[nb,b])
		Constructing wrapper function "flatBounds"...
		  be,bd = flatBounds(elev,erodep,bid,gbounds,[nb,b])
		Constructing wrapper function "slpBounds"...
		  be,bd = slpBounds(elev,erodep,bid,gbounds,[nb,b])
		Constructing wrapper function "setHillslopeCoeff"...
		  dcoeff = setHillslopeCoeff(nb,kd)
		Constructing wrapper function "setDiffusionCoeff"...
		  dcoeff = setDiffusionCoeff(kd,limit,elev,elev0,dh,[nb])
		Constructing wrapper function "explicitDiff"...
		  newz = explicitDiff(kd,limit,elev,elev0,dh,[nb])
		Constructing wrapper function "distributeHeight"...
		  nelev,nsed = distributeHeight(inids,sl,elev,elev0,sed,[nb])
		Constructing wrapper function "distributeVolume"...
		  nsed = distributeVolume(inids,sl,elev,elev0,sed,[nb])
		Constructing wrapper function "diffusionDT"...
		  ierr = diffusionDT(dm,hlocal,hl0,bounds,iters,itflx,inids,sflux,skd,okd,sl,[nb])
		Constructing wrapper function "minHeight"...
		  hmin = minHeight(inids,elev,[nb])
		Constructing wrapper function "pitData"...
		  tmp3 = pitData(rank_bn,pnode,inids,natural,[nb,nb1,nb2])
		Constructing wrapper function "MFDreceivers"...
		  rcv,slope,dist,wgt = MFDreceivers(nrcv,inids,elev,[nb])
		Constructing wrapper function "defineTIN"...
		  ngbnb,ngbid,edgelgt,vorodist = defineTIN(coords,cells_nodes,cells_edges,edges_nodes,area,circumcenter,[n,nb,m])
		Constructing wrapper function "defineGTIN"...
		  ngbnb,ngbid = defineGTIN(nb,cells_nodes,edges_nodes,[n,m])
	Wrote C/API module "_fortran" to file "build/src.linux-x86_64-2.7/fortran/_fortranmodule.c"
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran' to include_dirs.
creating build/src.linux-x86_64-2.7/build
creating build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7
creating build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran
copying /usr/local/lib/python2.7/dist-packages/numpy/f2py/src/fortranobject.c -> build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran
copying /usr/local/lib/python2.7/dist-packages/numpy/f2py/src/fortranobject.h -> build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran
build_src: building npy-pkg config files
running build_py
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/eSCAPE
copying eSCAPE/__init__.py -> build/lib.linux-x86_64-2.7/eSCAPE
creating build/lib.linux-x86_64-2.7/eSCAPE/tools
copying eSCAPE/tools/__init__.py -> build/lib.linux-x86_64-2.7/eSCAPE/tools
copying eSCAPE/tools/outmesh.py -> build/lib.linux-x86_64-2.7/eSCAPE/tools
copying eSCAPE/tools/inputparser.py -> build/lib.linux-x86_64-2.7/eSCAPE/tools
creating build/lib.linux-x86_64-2.7/eSCAPE/mesher
copying eSCAPE/mesher/unstructuredmesh.py -> build/lib.linux-x86_64-2.7/eSCAPE/mesher
copying eSCAPE/mesher/__init__.py -> build/lib.linux-x86_64-2.7/eSCAPE/mesher
creating build/lib.linux-x86_64-2.7/eSCAPE/pit
copying eSCAPE/pit/__init__.py -> build/lib.linux-x86_64-2.7/eSCAPE/pit
copying eSCAPE/pit/pitfillunst.py -> build/lib.linux-x86_64-2.7/eSCAPE/pit
creating build/lib.linux-x86_64-2.7/eSCAPE/flow
copying eSCAPE/flow/__init__.py -> build/lib.linux-x86_64-2.7/eSCAPE/flow
copying eSCAPE/flow/surfprocplex.py -> build/lib.linux-x86_64-2.7/eSCAPE/flow
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building 'eSCAPE._fortran' extension
compiling C sources
C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC

creating build/temp.linux-x86_64-2.7/build
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/build
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran
compile options: '-I/live/lib/petsc/arch-linux2-c-opt/include -I/live/lib/petsc/include -I/usr/local/lib/python2.7/dist-packages/petsc4py/include -I. -Ibuild/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c'
x86_64-linux-gnu-gcc: build/src.linux-x86_64-2.7/fortran/_fortranmodule.c
x86_64-linux-gnu-gcc: build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran/fortranobject.c
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran/fortranobject.h:13,
                 from build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran/fortranobject.c:2:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran/fortranobject.h:13,
                 from build/src.linux-x86_64-2.7/fortran/_fortranmodule.c:16:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
build/src.linux-x86_64-2.7/fortran/_fortranmodule.c:149:12: warning: 'f2py_size' defined but not used [-Wunused-function]
 static int f2py_size(PyArrayObject* var, ...)
            ^
compiling Fortran 90 module sources
creating build/temp.linux-x86_64-2.7/eSCAPE
Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
creating build/temp.linux-x86_64-2.7/fortran
compile options: '-I/live/lib/petsc/arch-linux2-c-opt/include -I/live/lib/petsc/include -I/usr/local/lib/python2.7/dist-packages/petsc4py/include -I. -Ibuild/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c'
extra options: '-Jbuild/temp.linux-x86_64-2.7/eSCAPE -Ibuild/temp.linux-x86_64-2.7/eSCAPE'
extra f90 options: '-fPIC -O3'
gfortran:f90: fortran/functions.F90
/usr/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran/_fortranmodule.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortran/fortranobject.o build/temp.linux-x86_64-2.7/fortran/functions.o -L/live/lib/petsc/arch-linux2-c-opt/lib -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5 -Wl,-rpath=/live/lib/petsc/arch-linux2-c-opt/lib -lpetsc -lgfortran -o build/lib.linux-x86_64-2.7/eSCAPE/_fortran.so
running install_lib
creating /usr/local/lib/python2.7/dist-packages/eSCAPE
creating /usr/local/lib/python2.7/dist-packages/eSCAPE/pit
copying build/lib.linux-x86_64-2.7/eSCAPE/pit/__init__.py -> /usr/local/lib/python2.7/dist-packages/eSCAPE/pit
copying build/lib.linux-x86_64-2.7/eSCAPE/pit/pitfillunst.py -> /usr/local/lib/python2.7/dist-packages/eSCAPE/pit
creating /usr/local/lib/python2.7/dist-packages/eSCAPE/tools
copying build/lib.linux-x86_64-2.7/eSCAPE/tools/__init__.py -> /usr/local/lib/python2.7/dist-packages/eSCAPE/tools
copying build/lib.linux-x86_64-2.7/eSCAPE/tools/outmesh.py -> /usr/local/lib/python2.7/dist-packages/eSCAPE/tools
copying build/lib.linux-x86_64-2.7/eSCAPE/tools/inputparser.py -> /usr/local/lib/python2.7/dist-packages/eSCAPE/tools
copying build/lib.linux-x86_64-2.7/eSCAPE/_fortran.so -> /usr/local/lib/python2.7/dist-packages/eSCAPE
copying build/lib.linux-x86_64-2.7/eSCAPE/__init__.py -> /usr/local/lib/python2.7/dist-packages/eSCAPE
creating /usr/local/lib/python2.7/dist-packages/eSCAPE/mesher
copying build/lib.linux-x86_64-2.7/eSCAPE/mesher/unstructuredmesh.py -> /usr/local/lib/python2.7/dist-packages/eSCAPE/mesher
copying build/lib.linux-x86_64-2.7/eSCAPE/mesher/__init__.py -> /usr/local/lib/python2.7/dist-packages/eSCAPE/mesher
creating /usr/local/lib/python2.7/dist-packages/eSCAPE/flow
copying build/lib.linux-x86_64-2.7/eSCAPE/flow/__init__.py -> /usr/local/lib/python2.7/dist-packages/eSCAPE/flow
copying build/lib.linux-x86_64-2.7/eSCAPE/flow/surfprocplex.py -> /usr/local/lib/python2.7/dist-packages/eSCAPE/flow
byte-compiling /usr/local/lib/python2.7/dist-packages/eSCAPE/pit/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/eSCAPE/pit/pitfillunst.py to pitfillunst.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/eSCAPE/tools/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/eSCAPE/tools/outmesh.py to outmesh.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/eSCAPE/tools/inputparser.py to inputparser.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/eSCAPE/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/eSCAPE/mesher/unstructuredmesh.py to unstructuredmesh.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/eSCAPE/mesher/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/eSCAPE/flow/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/eSCAPE/flow/surfprocplex.py to surfprocplex.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/eSCAPE-0.1.egg-info
running install_clib
customize UnixCCompiler
```

**Comment by tristan-salles** [comment]
Hi again @johnjarmitage,

I did compile the code using python3.7 and _conda_ for `petsc` install I found out that the library isn't named properly. As an example in my case the **_fortran.so** library is named **_fortran.cpython-37m-darwin.so**. A quick fix consists in renaming the library ... then the package seems to be loading in python...

Something like this in your case:

```
cd  /home/armitage/anaconda3/envs/escape/lib/python3.6/site-packages/eSCAPE
cp _fortran.cpython-36m-darwin.so _fortran.so
```

**Comment by johnjarmitage** [comment]
Hi @tristan-salles,

Thanks for all the help. It looks like it works!

**Comment by johnjarmitage** [comment]
In fact I have had mixed success. First on line 77 of `__init.py__` my install did not like `import tools`. This import did not look like it was necessary, so I commented it out. Then I went to the eSCAPE-demos and tried the slope demo. All worked fine until after ` Create DMPlex`. Here the code failed with the following error:
```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-28-8f870f2fa4f6> in <module>
      2 
      3 # Reading input file
----> 4 model = eSCAPE.LandscapeEvolutionModel('input.yml')
      5 
      6 # Running model

~/anaconda3/envs/escape/lib/python3.6/site-packages/eSCAPE/__init__.py in LandscapeEvolutionModel(filename, *args, **kwargs)
    216             return
    217 
--> 218     return LandscapeEvolutionModelClass(filename, *args, **kwargs)

~/anaconda3/envs/escape/lib/python3.6/site-packages/eSCAPE/__init__.py in __init__(self, filename, verbose, showlog, *args, **kwargs)
    113             _ReadYaml.__init__(self, filename)
    114 
--> 115             _UnstMesh.__init__(self, self.meshFile, *args, **kwargs)
    116 
    117             _WriteMesh.__init__(self)

~/anaconda3/envs/escape/lib/python3.6/site-packages/eSCAPE/mesher/unstructuredmesh.py in __init__(self, filename, dim)
    105         # Create DMPlex
    106         t = clock()
--> 107         self._create_DMPlex(dim, coords, cells, elev)
    108         if MPIrank == 0 and self.verbose:
    109             print('Creating Petsc DMPlex (%0.02f seconds)'% (clock() - t))

~/anaconda3/envs/escape/lib/python3.6/site-packages/eSCAPE/mesher/unstructuredmesh.py in _create_DMPlex(self, dim, coords, cells, elev)
    246         # Define one DoF on the nodes
    247         origSect = self.dm.createSection(1, [1,0,0])
--> 248         origSect.setFieldName(0, "points")
    249         origSect.setUp()
    250         self.dm.setDefaultSection(origSect)

PETSc/Section.pyx in petsc4py.PETSc.Section.setFieldName()

Error: error code 63
[0] PetscSectionSetFieldName() line 426 in /home/conda/feedstock_root/build_artifacts/petsc_1556557138679/work/src/vec/is/utils/vsectionis.c
[0] Argument out of range
[0] Section field 0 should be in [0, 0)
```
Sorry :-(

**Comment by tristan-salles** [comment]
Sorry for that! There are actually some new ways of defining fields within the latest **petsc** release. 
I am currently making the required modifications to comply with these recent changes... I will get back to you when it's done!

**Comment by tristan-salles** [comment]
When updating eSCAPE to the newer version of `PETSC>=3.11`, I had to make modifications to the code to comply with some new methods to define fields... I have created a new branch petsc3.11.2 that account for those changes in `Python3.5`.   

I have added some guidelines to install this new branch of eSCAPE on Linux system: 
+ [Linux dependency](https://github.com/Geodels/eSCAPE/wiki/Dependency)

I have also built a `Docker` container (**escape-docker:python3**) to run this version with `kitematics`.

**Comment by tristan-salles** [comment]
In your case I think you only need to do the following commands after changing PETSC_DIR and PETSC_ARCH the :

```bash
export F90=gfortran 
git clone -b python3 https://github.com/Geodels/fillit.git  
cd fillit  
python3 setup.py install
```

and 

```bash
git clone -b petsc3.11.2 https://github.com/Geodels/eSCAPE.git 
cd eSCAPE 
export F90=gfortran 
export PETSC_DIR=/opt/petsc 
export PETSC_ARCH=arch-linux-c-opt 
python setup.py install 
```

FInally to get the examples if needed:
```bash
git clone -b petsc3.11.2 https://github.com/Geodels/eSCAPE-demo.git 
```

**Comment by johnjarmitage** [comment]
Hi Tristan. This is fantastic. I am away from my workstation for the rest of this month, but I will test it in August.
